In [ ]:
# NumPy numerical python 


In [4]:
import numpy as np # np is alias 

In [5]:
help(np.abs)

Help on ufunc:

absolute = <ufunc 'absolute'>
    absolute(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Calculate the absolute value element-wise.
    
    ``np.abs`` is a shorthand for this function.
    
    Parameters
    ----------
    x : array_like
        Input array.
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retain its original value.
        Note that if an uninitialized 

In [6]:
np

<module 'numpy' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numpy/__init__.py'>

In [7]:
my_array = np.array([1,2,3,4,5])

In [8]:
type(my_array)

numpy.ndarray

In [9]:
# how to fetch elements in array

In [10]:
my_array[-1]

5

In [11]:
my_array[0]

1

In [12]:
my_array[1]

2

In [13]:
# get second last element 
my_array[-2]

4

In [14]:
# slicing  3,4
my_array[2:4:1]

array([3, 4])

In [15]:
my_array[2:]

array([3, 4, 5])

In [16]:
my_array[:5]

array([1, 2, 3, 4, 5])

In [17]:
my_array[:4]

array([1, 2, 3, 4])

In [24]:
# define two dilemtion array
arr2= np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
# get dimention of the array 
arr2.ndim

2

In [23]:
# get shape of the column - number fo row and columns
arr2.shape

(3, 3)

In [26]:
# get total number of elements on array 
arr2.size

9

In [30]:
arr2.max()

9

In [33]:
# zero matrix and 1 matrix
zero=np.zeros((3,4)) # default as float 
zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [36]:
zeroint=np.zeros((3,2),dtype=int)
zeroint

array([[0, 0],
       [0, 0],
       [0, 0]])

In [37]:
onematrix=np.ones((3,3)) # as float
onematrix

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [39]:
onematrixint=np.ones((2,3),dtype=int)
onematrixint

array([[1, 1, 1],
       [1, 1, 1]])

In [41]:
#create matrix with default value a,10,30 etc 
full_matrx=np.full((3,3),fill_value=10)
full_matrx

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [43]:
fullmata=np.full((3,4),fill_value='a')
fullmata

array([['a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a']], dtype='<U1')

In [45]:
full3=np.full((9,9),fill_value=1)
full3

array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [60]:
# This is a level 1 heading

In [58]:
#identity matrix - same column as row 
np.eye(5,dtype=int,k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]])

# a range function - create one dimetional array 

In [68]:
arange1=np.arange(0,10)
arange1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
arange2=np.arange(1,10,2)
arange2

array([1, 3, 5, 7, 9])

In [76]:
#Transpose 
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [83]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [78]:
arr.shape

(2, 5)

In [79]:
arr_transpose=np.transpose(arr)

In [80]:
arr_transpose


array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [81]:
arr_transpose.shape

(5, 2)

In [84]:
array1d=np.array([1,2,3,4,5,6])

In [87]:
array1d.shape

(6,)

In [88]:
array1d.T.shape

(6,)

#### reshape the given array , condition is resize aaray size must be same 

In [90]:
arr=np.arange(0,10)

In [93]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
arr.size

10

In [95]:
arr2=arr.reshape(2,5)

In [96]:

arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [97]:
arr2.size

10

### mathimatical manipulation + - /


In [116]:
x= np.array([[1,2,3],[5,6,7]])
x

array([[1, 2, 3],
       [5, 6, 7]])

In [117]:
y= np.array([[1,2,3,4],[5,6,7,8]])

In [105]:
y

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [118]:
x+y

ValueError: operands could not be broadcast together with shapes (2,3) (2,4) 

In [107]:
x-y

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [108]:
x/y

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [111]:
np.add(x,y)

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [112]:
np.subtract(x,y)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [113]:
np.divide(x,y)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [114]:
# element wise multiplicaiton 
np.multiply(x,y)

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [115]:
x*y

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

# matrix multiplicaiton 


In [125]:
x=np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [126]:
y=np.array([[1,2],[3,4]])
y

array([[1, 2],
       [3, 4]])

In [127]:
x@y

array([[ 7, 10],
       [15, 22]])

In [124]:
x@y

array([[ 7, 10],
       [15, 22]])

In [128]:
np.matmul(x,y)

array([[ 7, 10],
       [15, 22]])

In [129]:
np.dot(x,y)

array([[ 7, 10],
       [15, 22]])

# Flatten the array

In [130]:
flatten=np.array([[1,2,3],[4,5,6]])

In [131]:
flatten

array([[1, 2, 3],
       [4, 5, 6]])

In [132]:
flatten.flatten()


array([1, 2, 3, 4, 5, 6])

In [138]:
flatten.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [153]:
arr=np.array([[1,1,1,1],[1,0,0,1],[1,1,1,1]])
arr

array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

In [147]:
result_2 =arr+1
result_2

array([[2, 2, 2, 2],
       [2, 1, 1, 2],
       [2, 2, 2, 2]])

In [152]:
result_2%2

array([[0, 0, 0, 0],
       [0, 1, 1, 0],
       [0, 0, 0, 0]])

# horizinatal stoking and vertical stoking 

In [154]:
x=np.array([[1,2],[3,4]])

In [155]:
x

array([[1, 2],
       [3, 4]])

In [170]:
y =np.array([[5,6],[7,8]])
y

array([[5, 6],
       [7, 8]])

In [171]:
np.hstack((x,y))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [172]:
np.hstack((y,x))

array([[5, 6, 1, 2],
       [7, 8, 3, 4]])

In [173]:
np.vstack((x,y))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [175]:
# create three 3*# identity matxt and try to do vstack and hstack 

In [184]:
m1=np.eye(3,dtype=int)
m1

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [185]:
m2=np.eye(3,dtype=int)
m2

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [186]:
m3=np.eye(3,dtype=int)
m3

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [187]:
np.vstack((m1,m2,m3))

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [188]:
np.hstack((m1,m2,m3))

array([[1, 0, 0, 1, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 1, 0, 0, 1, 0],
       [0, 0, 1, 0, 0, 1, 0, 0, 1]])

In [192]:
# given a array 
# Given array 
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [197]:
transposed = a.transpose()
transposed

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [198]:
transposed.reshape(2,6)

array([[ 1,  5,  9,  2,  6, 10],
       [ 3,  7, 11,  4,  8, 12]])